site_name: rides
site_description: RESTful API using DRF for managing ride info
repo_url: https://github.com/patpatpatpatpat/ridez_api
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/patpatpatpatpat">patpatpatpatpat</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
