# Generated by Django 5.1.5 on 2025-01-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_phone_number_ride_rideevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('RIDER', 'Rider'), ('DRIVER', 'Driver'), ('BOTH', 'Both'), ('ADMIN', 'Admin')], default='ADMIN', max_length=10),
            preserve_default=False,
        ),
    ]
